// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtUqSu3i8XHGQwL9epWNL8qDgZsdpfztY',
    appId: '1:964589519703:web:2bb96c64a42dce3b817412',
    messagingSenderId: '964589519703',
    projectId: 'fir-notesapp-b071e',
    authDomain: 'fir-notesapp-b071e.firebaseapp.com',
    storageBucket: 'fir-notesapp-b071e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzoc7NUhJ43TMYxEuNrKODc_nSof6hNRI',
    appId: '1:964589519703:android:d22d270c61f6b4c2817412',
    messagingSenderId: '964589519703',
    projectId: 'fir-notesapp-b071e',
    storageBucket: 'fir-notesapp-b071e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuUcQMxtGT1KeSQMuaUPDbn1Z1MCb5_uA',
    appId: '1:964589519703:ios:133db504cee4f742817412',
    messagingSenderId: '964589519703',
    projectId: 'fir-notesapp-b071e',
    storageBucket: 'fir-notesapp-b071e.firebasestorage.app',
    iosBundleId: 'com.example.myWalletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuUcQMxtGT1KeSQMuaUPDbn1Z1MCb5_uA',
    appId: '1:964589519703:ios:133db504cee4f742817412',
    messagingSenderId: '964589519703',
    projectId: 'fir-notesapp-b071e',
    storageBucket: 'fir-notesapp-b071e.firebasestorage.app',
    iosBundleId: 'com.example.myWalletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtUqSu3i8XHGQwL9epWNL8qDgZsdpfztY',
    appId: '1:964589519703:web:234dbd0d45a1b05b817412',
    messagingSenderId: '964589519703',
    projectId: 'fir-notesapp-b071e',
    authDomain: 'fir-notesapp-b071e.firebaseapp.com',
    storageBucket: 'fir-notesapp-b071e.firebasestorage.app',
  );
}